baseUrl: http://apresgilles.com
title: Après Gilles
theme: gohugo-theme-ananke
metaDataFormat: yaml
languageCode: en-us
defaultContentLanguage: en
permalinks:
  post: /:year/:month/:day/:title/
canonifyURLS: true
newContentEditor: vim
sectionPagesMenu: main
paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
author:
  name: Gnafron

params:
  favicon: ''
  description: Après Gilles
  facebook: ''
  twitter: ''
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  background_color_class: bg-black
  featured_image: /images/gohugo-default-sample-hero-image.jpg
  recent_posts_number: 5
