baseUrl: http://apresgilles.com
title: Après Gilles
theme: potato-dark
languageCode: en-US
defaultContentLanguage: fr-FR
metaDataFormat: yaml
canonifyURLS: true
permalinks:
  posts: /:year/:month/:day/:title
editor: vim
author:
  name: Nicolas

